#!/bin/bash

set -eu

function test() {
  local version=$1
  echo "----------------------------------------------------------------------"
  echo "[$version]"
  echo "----------------------------------------------------------------------"

  docker run --rm -v "$PWD:/app" -w /app crystallang/crystal:$version make ci
}

test 0.27.2
test 1.21.1
